name: 🐛 Bug
description: Report a bug
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the sections below to help everyone identify and fix the bug
  - type: textarea
    id: description
    attributes:
      label: Describe your issue
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
      1. Do to '...'
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What was the expected result?
      placeholder: I expected this to happen
  - type: textarea
    id: screenshots
    attributes:
      label: Put here any screenshots or videos (optional)
  - type: dropdown
    id: assign
    attributes:
      label: "Would you like to work on this issue?"
      options:
        - "Yes"
  - type: markdown
    attributes:
      value: |
        Thanks for reporting this issue! We will get back to you as soon as possible.